cloud:
  aws:
    credentials:
      access-key: AKIAZI2LHIRD2W6XUOI7
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: petpulse


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080
